name: chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.0.15
  intl: ^0.18.1
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^19.0.0
  provider: ^6.1.4
  hive_flutter: ^1.1.0
  logging: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
